---

- name: Create Arista VLANs
  hosts: arista

  tasks:
    - name: create VLANs
      eos_vlan: name={{item.name}} vlanid={{item.vlanid}}
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

      with_items:
        - {name: YELLOW, vlanid: 101} 
        - {name: PURPLE, vlanid: 102}
        - {name: GREEN, vlanid: 103}
