---

- name: Configure Arista Ethernet interface
  hosts: arista

  tasks:
    - name: Setting Ethernet5
      eos_interface: name=Ethernet5 description="*** IN USE ***"
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

    - name: Set Switchport config
      eos_switchport: name=Ethernet5 mode=access access_vlan=101
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https
